spring:
  application:
    name: api
  profiles:
    include: secret

jwt:
  header: Authorization
  secret:
    key: EIJXbcvMJcZRXQ8EhR4x5Cs3YVBd+B77wVnZv0U0Aac=
    token-validity-in-seconds: 3600

logging:
  level:
    org:
      springframework: DEBUG

openai:
  api:
    key:

kakao:
  api:
    key: ${KAKAO_KEY}

socketio:
  server:
    hostname: 127.0.0.1
    port: 8081