spring:
  application:
    name: api

jwt:
  header: Authorization
  secret:
    key: EIJXbcvMJcZRXQ8EhR4x5Cs3YVBd+B77wVnZv0U0Aac=
    token-validity-in-seconds: 3600

logging:
  level:
    org:
      springframework=DEBUG:

openai:
  api:
    key:
